version: '3.8'

services:
  # Database
  mysql:
    image: mysql:8.0
    container_name: payment-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: payment_system
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: payment_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-compose/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - payment-network

  # API Gateway Service
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - PAYMENT_SERVICE_URL=http://payment-service:8081
      - MERCHANT_SERVICE_URL=http://merchant-service:8082
      - NOTIFICATION_SERVICE_URL=http://notification-service:8083
    depends_on:
      - payment-service
      - merchant-service
      - notification-service
    networks:
      - payment-network

  # Payment Service
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payment_system
      - SPRING_DATASOURCE_USERNAME=payment_user
      - SPRING_DATASOURCE_PASSWORD=payment_password
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - mysql
    networks:
      - payment-network

  # Merchant Service
  merchant-service:
    build: ./merchant-service
    container_name: merchant-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payment_system
      - SPRING_DATASOURCE_USERNAME=payment_user
      - SPRING_DATASOURCE_PASSWORD=payment_password
    depends_on:
      - mysql
    networks:
      - payment-network

  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payment_system
      - SPRING_DATASOURCE_USERNAME=payment_user
      - SPRING_DATASOURCE_PASSWORD=payment_password
    depends_on:
      - mysql
    networks:
      - payment-network

volumes:
  mysql_data:

networks:
  payment-network:
    driver: bridge
